export type FeaturedGuide = {
  title: string;
  summary: string;
  steps: string[];
  takeaway: string;
  code?: string;
};

export type LearningArea = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  icon: string;
  color: string;
  topics: string[];
  featured: FeaturedGuide[];
};

export const learningAreas: LearningArea[] = [
  {
    slug: "playbooks",
    title: "Developer Playbooks",
    eyebrow: "Repeatable process",
    description: "Step-by-step approaches for situations developers face in real projects.",
    icon: "📖",
    color: "#38bdf8",
    topics: [
      "Approach an unfamiliar codebase",
      "Debug a production issue",
      "Investigate a slow API",
      "Change a database schema safely",
      "Plan a large refactor",
      "Review a pull request",
      "Write a technical design document",
      "Release a risky feature",
      "Roll back a deployment",
      "Respond to an incident",
      "Write a postmortem",
      "Evaluate a dependency",
      "Manage technical debt",
    ],
    featured: [
      {
        title: "Approach an unfamiliar codebase",
        summary: "Build a reliable mental model before making broad changes.",
        steps: [
          "Run the application and one representative test before editing anything.",
          "Locate entry points, route definitions, configuration, and package manifests.",
          "Trace one user action through the interface, API, business logic, and persistence.",
          "Read recent pull requests to learn conventions and active areas.",
          "Make one small change and verify your understanding with a maintainer.",
        ],
        takeaway: "Follow real execution paths; do not try to read every file.",
      },
      {
        title: "Release a risky feature",
        summary: "Reduce blast radius and make recovery a normal part of the plan.",
        steps: [
          "Define success, failure, owners, and observable signals.",
          "Separate deployment from release with a feature flag when possible.",
          "Verify backward compatibility and rehearse the rollback.",
          "Release to a small cohort and watch technical and product signals.",
          "Expand gradually, document the result, and remove temporary controls.",
        ],
        takeaway: "A rollout plan without a tested rollback is incomplete.",
      },
      {
        title: "Evaluate a dependency",
        summary: "Choose libraries using evidence instead of popularity alone.",
        steps: [
          "Write down the exact problem and compare against a small in-house solution.",
          "Check maintenance activity, release history, license, size, and platform support.",
          "Review its security history and transitive dependencies.",
          "Prototype the hardest integration and removal path.",
          "Record the decision, owner, upgrade plan, and exit strategy.",
        ],
        takeaway: "The true cost includes upgrades, incidents, learning, and eventual removal.",
      },
    ],
  },
  {
    slug: "debugging",
    title: "Debugging Challenges",
    eyebrow: "Practice",
    description: "Reason through symptoms, evidence, root causes, fixes, and prevention.",
    icon: "🪲",
    color: "#f97316",
    topics: [
      "React infinite render",
      "Missing effect cleanup",
      "API request race condition",
      "SQL N+1 query",
      "Broken authorization check",
      "Memory leak",
      "Unhandled promise rejection",
      "Slow database query",
      "Duplicate webhook processing",
      "Incorrect cursor pagination",
      "Stale cache",
      "Docker networking failure",
      "Works locally but fails in CI",
    ],
    featured: [
      {
        title: "React infinite render",
        summary: "The page freezes and the console reports too many renders.",
        code: "function Profile({ user }) {\n  const [name, setName] = useState(\"\");\n  setName(user.name);\n  return <input value={name} />;\n}",
        steps: [
          "Symptom: rendering calls a state setter, which schedules another render.",
          "Root cause: synchronization is happening unconditionally in the component body.",
          "Fix: initialize from props, derive the value, or synchronize in a carefully scoped effect.",
          "Prevention: treat rendering as pure and avoid duplicated state.",
        ],
        takeaway: "Do not update state during render.",
      },
      {
        title: "Duplicate webhook processing",
        summary: "A customer receives the same fulfillment twice even though the provider sent a valid event.",
        code: "await fulfillOrder(event.data.object);\nreturn new Response(\"ok\");",
        steps: [
          "Evidence: logs show the same provider event ID delivered more than once.",
          "Root cause: webhook delivery is at-least-once, but the consumer assumes exactly once.",
          "Fix: persist the provider event ID under a unique constraint before side effects.",
          "Prevention: make handlers idempotent and provide safe replay tooling.",
        ],
        takeaway: "Retries are normal; duplicate side effects are a design bug.",
      },
      {
        title: "Works locally, fails in CI",
        summary: "Tests pass on a laptop but fail intermittently in a clean Linux runner.",
        code: "import config from \"./Config\";\n// Actual file: ./config.ts",
        steps: [
          "Compare operating system, runtime version, environment variables, and lockfile usage.",
          "Run from a clean checkout with the same command and runtime as CI.",
          "Check case-sensitive paths, timezone assumptions, ordering, ports, and shared test state.",
          "Pin the environment and remove the hidden dependency.",
        ],
        takeaway: "Reproduce the environment before changing the test.",
      },
    ],
  },
  {
    slug: "system-design",
    title: "System Design",
    eyebrow: "Architecture",
    description: "Design useful systems from requirements through trade-offs and failure modes.",
    icon: "🏗️",
    color: "#a78bfa",
    topics: [
      "URL shortener",
      "Notification service",
      "Real-time chat",
      "File-upload service",
      "Payment system",
      "Authentication service",
      "Search service",
      "News feed",
      "Analytics pipeline",
      "Appointment booking",
      "Multi-tenant SaaS",
      "Rate limiter",
      "Background job system",
    ],
    featured: [
      {
        title: "System-design method",
        summary: "Use the same disciplined sequence before drawing boxes.",
        steps: [
          "Clarify users, core flows, scale, latency, availability, consistency, privacy, and budget.",
          "Define APIs and the minimum data model.",
          "Draw a simple end-to-end design that works at today's scale.",
          "Identify bottlenecks, dependencies, failure modes, and observability.",
          "Evolve only the constrained parts and explain each trade-off.",
        ],
        takeaway: "Requirements drive architecture; diagrams do not create requirements.",
      },
      {
        title: "Notification service",
        summary: "Deliver email, SMS, and push messages without blocking product requests.",
        steps: [
          "Accept a typed notification request with an idempotency key.",
          "Persist intent, preferences, template version, and delivery status.",
          "Queue one job per channel and isolate provider adapters.",
          "Retry transient failures, dead-letter poison jobs, and disable invalid destinations.",
          "Measure queued, accepted, delivered, failed, opened, and acted-on separately.",
        ],
        takeaway: "Provider acceptance is not the same as user delivery.",
      },
      {
        title: "Multi-tenant SaaS",
        summary: "Keep tenant data isolated while supporting shared infrastructure.",
        steps: [
          "Resolve trusted tenant context during authentication.",
          "Include tenant ownership in schemas, indexes, caches, jobs, and object storage.",
          "Enforce isolation at every data-access boundary.",
          "Add tenant-aware quotas, audit logs, exports, and deletion.",
          "Test cross-tenant access as a first-class security requirement.",
        ],
        takeaway: "Tenant isolation must survive every alternate access path.",
      },
    ],
  },
  {
    slug: "production",
    title: "Production Engineering",
    eyebrow: "Operate",
    description: "Ship observable, reliable systems and respond effectively when they fail.",
    icon: "📈",
    color: "#34d399",
    topics: [
      "Logs, metrics, and traces",
      "Health and readiness checks",
      "Dashboards and actionable alerts",
      "Service-level indicators and objectives",
      "Timeouts, retries, and backoff",
      "Circuit breakers",
      "Graceful degradation",
      "Load testing",
      "Capacity planning",
      "Disaster recovery",
      "Backup restore testing",
      "Zero-downtime deployments",
      "Canary releases",
      "Feature flags",
      "Incident command",
      "Blameless postmortems",
    ],
    featured: [
      {
        title: "Observability baseline",
        summary: "Give responders enough context to understand impact and isolate causes.",
        steps: [
          "Emit structured logs with request, user-safe, tenant, and trace identifiers.",
          "Measure request rate, errors, duration, and saturation.",
          "Trace important work across service and queue boundaries.",
          "Build dashboards around user journeys and service objectives.",
          "Alert on actionable symptoms instead of every internal anomaly.",
        ],
        takeaway: "Telemetry is useful when it helps answer a production question.",
      },
      {
        title: "Safe retry policy",
        summary: "Recover from transient failure without multiplying the incident.",
        steps: [
          "Retry only operations known to be safe or protected by idempotency.",
          "Set a deadline and use exponential backoff with jitter.",
          "Cap attempts and respect upstream Retry-After guidance.",
          "Avoid synchronized retries and nested retry multiplication.",
          "Record exhaustion and provide a dead-letter or recovery path.",
        ],
        takeaway: "Retries shift load through time; they do not remove load.",
      },
      {
        title: "Incident response",
        summary: "Restore service first, preserve clear ownership, then learn.",
        steps: [
          "Declare severity and assign incident lead, operations, and communications roles.",
          "Establish impact, recent changes, and a timestamped incident document.",
          "Mitigate through rollback, disablement, failover, or controlled degradation.",
          "Communicate on a predictable cadence until recovery is verified.",
          "Write a blameless postmortem and track prevention work to completion.",
        ],
        takeaway: "During an incident, coordination is a technical capability.",
      },
    ],
  },
  {
    slug: "security",
    title: "Security Checklists",
    eyebrow: "Protect",
    description: "Practical checks for common application boundaries and sensitive workflows.",
    icon: "🛡️",
    color: "#ef4444",
    topics: [
      "Authentication",
      "Authorization",
      "API security",
      "File uploads",
      "Payments",
      "Webhooks",
      "Password storage",
      "Sessions and cookies",
      "Secrets management",
      "Dependency security",
      "Sensitive logging",
      "SQL injection",
      "XSS and CSRF",
      "SSRF",
      "Rate limiting",
      "Multi-tenant isolation",
      "Mobile application security",
    ],
    featured: [
      {
        title: "Authorization checklist",
        summary: "Verify permission at the server boundary for every protected action.",
        steps: [
          "Authenticate the caller using a verified, non-expired session or token.",
          "Load the target resource and verify tenant, ownership, role, and action.",
          "Apply the same rules to bulk, export, background, and administrative paths.",
          "Return minimal information when access is denied.",
          "Log sensitive administrative decisions without logging secrets.",
        ],
        takeaway: "Knowing an object identifier never grants permission to use it.",
      },
      {
        title: "File-upload checklist",
        summary: "Treat file contents, names, metadata, and delivery as untrusted.",
        steps: [
          "Require authorization and limit count, size, and rate.",
          "Generate server-side names and store outside executable web roots.",
          "Check actual file signatures, not only extensions or client MIME types.",
          "Scan when appropriate and process in an isolated environment.",
          "Serve with safe content headers and short-lived authorized URLs.",
        ],
        takeaway: "Validation must cover storage and later delivery, not only upload.",
      },
      {
        title: "Secrets checklist",
        summary: "Minimize exposure and make credential rotation routine.",
        steps: [
          "Keep secrets out of source control, images, browser bundles, and logs.",
          "Use a secret manager and grant workloads least-privilege access.",
          "Prefer short-lived workload identity over long-lived keys.",
          "Rotate credentials and support overlapping keys during transitions.",
          "Audit access and maintain a tested response for accidental disclosure.",
        ],
        takeaway: "A secret without an owner and rotation path is future incident debt.",
      },
    ],
  },
  {
    slug: "code-review",
    title: "Code Review",
    eyebrow: "Quality",
    description: "Review correctness, clarity, risk, and operability while helping people grow.",
    icon: "🔎",
    color: "#22d3ee",
    topics: [
      "Correctness and edge cases",
      "Readability and naming",
      "Test quality",
      "Error handling",
      "Security and privacy",
      "Accessibility",
      "Performance",
      "Database impact",
      "Backward compatibility",
      "Observability",
      "Rollout risk",
      "Unnecessary complexity",
      "Constructive feedback",
    ],
    featured: [
      {
        title: "Review in layers",
        summary: "Start with intent and risk before discussing local style.",
        steps: [
          "Understand the user problem, acceptance criteria, and intended behavior.",
          "Check architecture, data flow, permissions, and failure behavior.",
          "Inspect tests, migrations, compatibility, and rollout strategy.",
          "Review readability, naming, duplication, and maintainability.",
          "Clearly label blocking issues, suggestions, questions, and praise.",
        ],
        takeaway: "Do not polish an implementation that solves the wrong problem.",
      },
      {
        title: "Give useful feedback",
        summary: "Make comments specific, respectful, and easy to act on.",
        steps: [
          "Describe the observed risk instead of judging the author.",
          "Ask a question when you may be missing context.",
          "Explain why a requested change matters.",
          "Offer an example without demanding your exact implementation.",
          "Resolve conversations explicitly after agreement or follow-up.",
        ],
        takeaway: "The goal is shared understanding and better software, not winning.",
      },
      {
        title: "Review production readiness",
        summary: "Look beyond whether the happy path compiles.",
        steps: [
          "Check logs, metrics, alerts, and actionable error context.",
          "Ask how partial failure, retries, duplicates, and timeouts behave.",
          "Verify migration order and compatibility with old clients or workers.",
          "Confirm rollout, rollback, and feature-flag ownership.",
          "Ensure support and on-call teams can diagnose the change.",
        ],
        takeaway: "A change is not complete until it can be operated safely.",
      },
    ],
  },
  {
    slug: "projects",
    title: "Project Blueprints",
    eyebrow: "Build",
    description: "Portfolio and learning projects that grow from fundamentals to production thinking.",
    icon: "🧰",
    color: "#f59e0b",
    topics: [
      "Developer portfolio",
      "Task manager",
      "E-commerce application",
      "Real-time chat",
      "Expense tracker",
      "Appointment system",
      "SaaS subscription app",
      "Mobile application",
      "Analytics dashboard",
      "Developer API",
    ],
    featured: [
      {
        title: "Task manager",
        summary: "A project that can grow with the developer instead of being rebuilt.",
        steps: [
          "Junior: CRUD tasks, validation, responsive UI, authentication, tests, and deployment.",
          "Mid: teams, roles, filters, cursor pagination, audit history, jobs, and observability.",
          "Senior: tenant isolation, SLOs, data migration, rate limits, threat model, and rollout plan.",
          "Document architecture, decisions, API contracts, and known trade-offs.",
          "Measure at least one user or system outcome.",
        ],
        takeaway: "Depth and operational quality are more valuable than another shallow project.",
      },
      {
        title: "Appointment system",
        summary: "Practice concurrency, time, notifications, and sensitive workflows.",
        steps: [
          "Model providers, availability, time zones, appointments, and cancellation policy.",
          "Prevent double booking with a database constraint or transactional lock.",
          "Send idempotent reminders and safely process provider callbacks.",
          "Protect personal information and record meaningful audit events.",
          "Test daylight-saving transitions, concurrent requests, and provider failure.",
        ],
        takeaway: "Business invariants belong in the data and service design.",
      },
      {
        title: "SaaS subscription app",
        summary: "Combine product flows with payments and operational concerns.",
        steps: [
          "Build tenant onboarding, roles, plans, and server-enforced entitlements.",
          "Use hosted checkout and verified, idempotent payment webhooks.",
          "Model trial, active, past-due, canceled, and recovery states.",
          "Add usage limits, audit logs, support tooling, and account deletion.",
          "Create dashboards for activation, payment failure, and system health.",
        ],
        takeaway: "Billing state is asynchronous; redirects are not authoritative.",
      },
    ],
  },
  {
    slug: "patterns",
    title: "Architecture Patterns",
    eyebrow: "Trade-offs",
    description: "Understand when patterns help, when they hurt, and what they cost.",
    icon: "🧩",
    color: "#c084fc",
    topics: [
      "Repository pattern",
      "Service layer",
      "Dependency injection",
      "Adapter pattern",
      "Strategy pattern",
      "Factory pattern",
      "Observer pattern",
      "State machines",
      "Event-driven architecture",
      "Modular monolith",
      "Microservices",
      "CQRS",
      "Saga pattern",
      "Transactional outbox",
      "Cache-aside",
      "Circuit breaker",
    ],
    featured: [
      {
        title: "Modular monolith",
        summary: "Keep one deployable application with deliberate internal boundaries.",
        steps: [
          "Organize around business capabilities instead of technical folders alone.",
          "Give modules explicit public interfaces and private implementation details.",
          "Avoid direct access to another module's internal tables or classes.",
          "Test boundaries and record dependency direction.",
          "Extract a service only when independent operation creates demonstrated value.",
        ],
        takeaway: "A well-structured monolith is often the simplest distributed-system strategy.",
      },
      {
        title: "Transactional outbox",
        summary: "Publish events without losing consistency between database writes and messaging.",
        steps: [
          "Write the business change and an outbox row in one database transaction.",
          "Have a relay publish pending rows to the broker.",
          "Mark delivery state or use change-data capture.",
          "Make consumers idempotent because publication can repeat.",
          "Monitor outbox age, failures, and relay throughput.",
        ],
        takeaway: "The pattern trades dual-write loss for retryable duplicate delivery.",
      },
      {
        title: "When not to use microservices",
        summary: "Avoid paying distributed-system costs before they solve a real constraint.",
        steps: [
          "Do not split solely because the codebase is messy; improve boundaries first.",
          "Check whether teams truly require independent deployment and scaling.",
          "Account for network failure, observability, contracts, security, and data ownership.",
          "Compare against modules, queues, read replicas, and separate workers.",
          "Extract incrementally with a clear owner and measurable benefit.",
        ],
        takeaway: "Microservices move complexity; they do not automatically remove it.",
      },
    ],
  },
  {
    slug: "templates",
    title: "Engineering Templates",
    eyebrow: "Reusable docs",
    description: "Practical starting points for decisions, incidents, releases, and collaboration.",
    icon: "📝",
    color: "#60a5fa",
    topics: [
      "Technical design document",
      "Architecture decision record",
      "Pull-request description",
      "Bug report",
      "Incident document",
      "Postmortem",
      "Runbook",
      "Release checklist",
      "Database migration plan",
      "API proposal",
      "Security review",
      "Project kickoff",
      "Career discussion",
      "Promotion evidence document",
    ],
    featured: [
      {
        title: "Technical design document",
        summary: "Align on the problem and consequential decisions before expensive implementation.",
        code: "# Context and problem\n# Goals / non-goals\n# Requirements and constraints\n# Proposed design\n# Alternatives considered\n# Data and API changes\n# Security and privacy\n# Failure modes and observability\n# Rollout / rollback\n# Open questions",
        steps: [
          "Keep the document proportional to the decision's cost and reversibility.",
          "Separate requirements from the proposed solution.",
          "Show alternatives and why they were rejected.",
          "Invite review from affected owners before implementation.",
        ],
        takeaway: "The value is alignment and decision quality, not document length.",
      },
      {
        title: "Blameless postmortem",
        summary: "Turn failure into prioritized system improvement.",
        code: "# Summary and customer impact\n# Detection\n# Timeline in UTC\n# Root and contributing factors\n# What went well / poorly\n# Recovery\n# Action items: owner + due date\n# Lessons",
        steps: [
          "Describe conditions and decisions without personal blame.",
          "Separate trigger, root cause, and contributing factors.",
          "Prioritize a small number of durable improvements.",
          "Track action items until completion.",
        ],
        takeaway: "A postmortem without completed follow-up work is only a story.",
      },
      {
        title: "Promotion evidence",
        summary: "Present impact and demonstrated scope without turning growth into a task count.",
        code: "# Target expectations\n# Impact examples\n## Context\n## My actions and decisions\n## Measured outcome\n## Collaboration and influence\n## What I learned\n# Feedback themes\n# Remaining gaps",
        steps: [
          "Use your company's actual expectations.",
          "Explain personal contribution without erasing the team.",
          "Prefer measurable outcomes and repeated behavior.",
          "Review gaps with your manager before a formal cycle.",
        ],
        takeaway: "Evidence should demonstrate sustained level, not one heroic project.",
      },
    ],
  },
  {
    slug: "interviews",
    title: "Interview Preparation",
    eyebrow: "Communicate",
    description: "Prepare for coding, design, debugging, and behavioral interviews at different levels.",
    icon: "🎯",
    color: "#fb7185",
    topics: [
      "Coding fundamentals",
      "Frontend interviews",
      "Backend interviews",
      "Mobile interviews",
      "System design",
      "Database design",
      "Debugging interviews",
      "Behavioral interviews",
      "Senior leadership questions",
      "Questions to ask employers",
    ],
    featured: [
      {
        title: "Coding interview method",
        summary: "Make reasoning, correctness, and collaboration visible.",
        steps: [
          "Restate the problem and clarify inputs, constraints, and edge cases.",
          "Work through a small example before selecting a solution.",
          "Explain complexity and trade-offs before coding.",
          "Implement in small steps with clear names.",
          "Test normal, boundary, empty, and failure cases aloud.",
        ],
        takeaway: "A correct solution nobody can follow is weaker than clear collaborative problem solving.",
      },
      {
        title: "Senior system-design interview",
        summary: "Show judgment and prioritization rather than listing technologies.",
        steps: [
          "Clarify business and reliability requirements.",
          "Estimate the dimensions that affect design.",
          "Start with the simplest end-to-end architecture.",
          "Explore the most important bottleneck and failure modes.",
          "Discuss security, observability, migration, cost, and team ownership.",
        ],
        takeaway: "Strong candidates explain why a component earns its complexity.",
      },
      {
        title: "Behavioral stories",
        summary: "Prepare evidence of ownership, conflict, failure, and growth.",
        steps: [
          "Use context, responsibility, action, result, and learning.",
          "Be precise about your contribution and the team's contribution.",
          "Include trade-offs and what made the situation difficult.",
          "Use measured outcomes when available.",
          "Explain what you would change with what you know now.",
        ],
        takeaway: "Reflection and judgment matter as much as the outcome.",
      },
    ],
  },
  {
    slug: "mistakes",
    title: "Common Developer Mistakes",
    eyebrow: "Learn faster",
    description: "Recognize habits that create hidden risk, complexity, and stalled growth.",
    icon: "⚠️",
    color: "#facc15",
    topics: [
      "Overengineering early",
      "Rewriting before understanding",
      "Ignoring failure states",
      "Using production as the test environment",
      "Logging sensitive data",
      "Retries without idempotency",
      "Optimizing without measurement",
      "Treating review as approval only",
      "Abstracting after one example",
      "Making everything a microservice",
      "Hiding uncertainty",
      "Becoming a single point of knowledge",
      "Confusing activity with impact",
    ],
    featured: [
      {
        title: "Overengineering early",
        summary: "Complexity is added for imagined futures while current requirements remain unclear.",
        steps: [
          "State today's requirements and likely near-term change.",
          "Choose the simplest design with a clear extension point.",
          "Measure the constraint before introducing infrastructure.",
          "Record what signal would justify the more complex design.",
        ],
        takeaway: "Good architecture preserves options without implementing every option.",
      },
      {
        title: "Rewriting before understanding",
        summary: "A replacement begins before existing behavior and constraints are known.",
        steps: [
          "Inventory users, integrations, undocumented behavior, and operational history.",
          "Add characterization tests around critical behavior.",
          "Identify whether the problem is boundaries, tooling, performance, or maintainability.",
          "Prefer incremental replacement with measurable checkpoints.",
        ],
        takeaway: "Old code often contains requirements that are not written anywhere else.",
      },
      {
        title: "Becoming the only expert",
        summary: "Being indispensable feels valuable but creates risk and limits growth.",
        steps: [
          "Document common operations and decisions.",
          "Pair on difficult work and rotate ownership.",
          "Create safe opportunities for others to make changes.",
          "Move from answering every question to teaching diagnostic approaches.",
        ],
        takeaway: "Senior engineers create capability, not dependency.",
      },
    ],
  },
];

export function getLearningArea(slug: string) {
  return learningAreas.find((area) => area.slug === slug);
}
